name: Test Deploy
on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Git Repo"
        uses: actions/checkout@v3
      - name: "Install a specific Node.js version"
        uses: actions/setup-node@v3
        with:
          node-version: 16
