name: Deploy_Provider_App
on: workflow_dispatch
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  Pre-requisite:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout Git Repo"
        uses: actions/checkout@v2    
      - name: "Setup Node 16 version"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Check Node and NPM version"
        run: | 
          node -v
          npm -v  

      
     


  
