name: my-1st-pipeline
on: workflow_dispatch
jobs:
  buildjob:
     runs-on: ubuntu-latest
     steps:
      - name: Install aws Cli
        run: echo $Date
        
      
    
          
          



          
        
  
       
        
      
     


