name: Deploy_Provider_App
on: workflow_dispatch
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  Pre-requisite:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Git Repo"
        uses: actions/checkout@v2
      - name: "Setup AWS CLI"
        run: |
          sudo apt remove -y awscli node npm
          echo "AWS Version"
          aws --version
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_DEFAULT_REGION
          echo "Node Version"
          sudo node -v
          echo "NPM Version"
          sudo npm -v
          git branch


  
