name: my-1st-pipeline
on: workflow_dispatch
jobs:
  buildjob:
     runs-on: ubuntu-latest
     steps:
       - name: 'Checkout'
         uses: actions/checkout@v2
       - name: List
         run: ls
        
      
    
          
          



          
        
  
       
        
      
     


