name: my-1st-pipeline
on: workflow_dispatch


jobs:
  buildjob:
     runs-on: ubuntu-latest
     steps:
     	 - name: "Checkout"
         uses: actions/checkout@v2        
       - name: Install aws Cli
         run: |
           sudo apt update
           sudo apt install awscli -y
           echo "Next Command will be displaying AWS Version"
           aws --version
           aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
           aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
           aws configure set region $AWS_DEFAULT_REGION
      

