name: my-1st-pipeline
on: workflow_dispatch
jobs:
  buildjob:
     runs-on: ubuntu-latest
     steps:
      - name: Build Application
        run: echo "Building"
      - name: Application testing
        run: echo "Tetsing"
      - name: Application deploying
        run: echo "Deploying"
     


