name: Deploy_Provider_App
on: workflow_dispatch
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  Pre-requisite:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: |
          echo "Node Version"
          sudo node -v
          echo "NPM Version"
          sudo npm -v



  
