name: my-1st-pipeline
on: workflow_dispatch
jobs:
  buildjob:
     runs-on: ubuntu-latest
     steps:
      - name: Build Application
        run: echo "Building"
        
  testjob:
    runs-on: ubuntu-latest
    steps:
       - name: Application testing
         run: echo "Tetsing"
  
  deployjob:
    runs-on: ubuntu-latest
    steps:
       - name: Application deploying
         run: echo "Deploying"
    
         

      
    
        
   
    
    
 
       
        
      
     


